# basic options
title: radlab2
author: salar
email: stefan@here.com
description: A wonderful site
twitter_username: salarrad
github_username:  salarirad

# Build settings
markdown: kramdown
theme: minima
